//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infinni.Node.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Infinni.Node.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not find any applications to start..
        /// </summary>
        internal static string CanNotFindAnyApplicationsToStart {
            get {
                return ResourceManager.GetString("CanNotFindAnyApplicationsToStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not find any applications to uninstall..
        /// </summary>
        internal static string CanNotFindAnyApplicationsToUninstall {
            get {
                return ResourceManager.GetString("CanNotFindAnyApplicationsToUninstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying package files for the application &apos;{0}&apos; (instance &apos;{1}&apos;)..
        /// </summary>
        internal static string CopyingPackageFiles {
            get {
                return ResourceManager.GetString("CopyingPackageFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying package files for the application &apos;{0}&apos; (instance &apos;{1}&apos;) completed successfully..
        /// </summary>
        internal static string CopyingPackageFilesCompleted {
            get {
                return ResourceManager.GetString("CopyingPackageFilesCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying package files for the application &apos;{0}&apos; (instance &apos;{1}&apos;) completed with errors: &apos;{2}&apos;..
        /// </summary>
        internal static string CopyingPackageFilesCompletedWithError {
            get {
                return ResourceManager.GetString("CopyingPackageFilesCompletedWithError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting package files for the application &apos;{0}&apos; (instance &apos;{1}&apos;)..
        /// </summary>
        internal static string DeletingPackageFiles {
            get {
                return ResourceManager.GetString("DeletingPackageFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting package files for the application &apos;{0}&apos; (instance &apos;{1}&apos;) completed successfully..
        /// </summary>
        internal static string DeletingPackageFilesCompleted {
            get {
                return ResourceManager.GetString("DeletingPackageFilesCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting package files for the application &apos;{0}&apos; (instance &apos;{1}&apos;) completed with errors: &apos;{2}&apos;..
        /// </summary>
        internal static string DeletingPackageFilesCompletedWithError {
            get {
                return ResourceManager.GetString("DeletingPackageFilesCompletedWithError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File &apos;{0}&apos; has rewritten. New source: &apos;{1}&apos;..
        /// </summary>
        internal static string FileHasRewritten {
            get {
                return ResourceManager.GetString("FileHasRewritten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing the application package &apos;{0}&apos; (instance &apos;{1}&apos;)..
        /// </summary>
        internal static string InstallingPackage {
            get {
                return ResourceManager.GetString("InstallingPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing the application package &apos;{0}&apos; (instance &apos;{1}&apos;) completed successfully..
        /// </summary>
        internal static string InstallingPackageCompleted {
            get {
                return ResourceManager.GetString("InstallingPackageCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing the application package &apos;{0}&apos; (instance &apos;{1}&apos;) completed with errors: &apos;{2}&apos;..
        /// </summary>
        internal static string InstallingPackageCompletedWithError {
            get {
                return ResourceManager.GetString("InstallingPackageCompletedWithError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing the service for the application &apos;{0}&apos; (instance &apos;{1}&apos;)..
        /// </summary>
        internal static string InstallingWorkerService {
            get {
                return ResourceManager.GetString("InstallingWorkerService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing the service for the application &apos;{0}&apos; (instance &apos;{1}&apos;) completed successfully..
        /// </summary>
        internal static string InstallingWorkerServiceCompleted {
            get {
                return ResourceManager.GetString("InstallingWorkerServiceCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing the service for the application &apos;{0}&apos; (instance &apos;{1}&apos;) completed with errors: &apos;{2}&apos;..
        /// </summary>
        internal static string InstallingWorkerServiceCompletedWithError {
            get {
                return ResourceManager.GetString("InstallingWorkerServiceCompletedWithError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application &apos;{0}&apos; (instance &apos;{1}&apos;) already installed..
        /// </summary>
        internal static string PackageAlreadyInstalled {
            get {
                return ResourceManager.GetString("PackageAlreadyInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package not found: Id=&apos;{0}&apos;, Version=&apos;{1}&apos;..
        /// </summary>
        internal static string PackageNotFound {
            get {
                return ResourceManager.GetString("PackageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registering service file.
        /// </summary>
        internal static string RegisterServiceFileStage {
            get {
                return ResourceManager.GetString("RegisterServiceFileStage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting the service for the application &apos;{0}&apos; (instance &apos;{1}&apos;)..
        /// </summary>
        internal static string StartingWorkerService {
            get {
                return ResourceManager.GetString("StartingWorkerService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting the service for the application &apos;{0}&apos; (instance &apos;{1}&apos;) completed successfully..
        /// </summary>
        internal static string StartingWorkerServiceCompleted {
            get {
                return ResourceManager.GetString("StartingWorkerServiceCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting the service for the application &apos;{0}&apos; (instance &apos;{1}&apos;) completed with errors: &apos;{2}&apos;..
        /// </summary>
        internal static string StartingWorkerServiceCompletedWithError {
            get {
                return ResourceManager.GetString("StartingWorkerServiceCompletedWithError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopping the service for the application &apos;{0}&apos; (instance &apos;{1}&apos;)..
        /// </summary>
        internal static string StoppingWorkerService {
            get {
                return ResourceManager.GetString("StoppingWorkerService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopping the service for the application &apos;{0}&apos; (instance &apos;{1}&apos;) completed successfully..
        /// </summary>
        internal static string StoppingWorkerServiceCompleted {
            get {
                return ResourceManager.GetString("StoppingWorkerServiceCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopping the service for the application &apos;{0}&apos; (instance &apos;{1}&apos;) completed with errors: &apos;{2}&apos;..
        /// </summary>
        internal static string StoppingWorkerServiceCompletedWithError {
            get {
                return ResourceManager.GetString("StoppingWorkerServiceCompletedWithError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstalling the service for the application &apos;{0}&apos; (instance &apos;{1}&apos;)..
        /// </summary>
        internal static string UninstallingWorkerService {
            get {
                return ResourceManager.GetString("UninstallingWorkerService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstalling the service for the application &apos;{0}&apos; (instance &apos;{1}&apos;) completed successfully..
        /// </summary>
        internal static string UninstallingWorkerServiceCompleted {
            get {
                return ResourceManager.GetString("UninstallingWorkerServiceCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstalling the service for the application &apos;{0}&apos; (instance &apos;{1}&apos;) completed with errors: &apos;{2}&apos;..
        /// </summary>
        internal static string UninstallingWorkerServiceCompletedWithError {
            get {
                return ResourceManager.GetString("UninstallingWorkerServiceCompletedWithError", resourceCulture);
            }
        }
    }
}
