//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infinni.Node.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Infinni.Node.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot execute stage: &apos;{0}&apos;..
        /// </summary>
        internal static string CantExecuteStage {
            get {
                return ResourceManager.GetString("CantExecuteStage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot rollback stage: &apos;{0}&apos;..
        /// </summary>
        internal static string CantRollbackStage {
            get {
                return ResourceManager.GetString("CantRollbackStage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting package files for the application &apos;{0}&apos; (instance &apos;{1}&apos;)..
        /// </summary>
        internal static string DeletingPackageFiles {
            get {
                return ResourceManager.GetString("DeletingPackageFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting package files for the application &apos;{0}&apos; (instance &apos;{1}&apos;) completed successfully..
        /// </summary>
        internal static string DeletingPackageFilesCompleted {
            get {
                return ResourceManager.GetString("DeletingPackageFilesCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting package files for the application &apos;{0}&apos; (instance &apos;{1}&apos;) completed with errors: &apos;{2}&apos;..
        /// </summary>
        internal static string DeletingPackageFilesCompletedWithError {
            get {
                return ResourceManager.GetString("DeletingPackageFilesCompletedWithError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing rollback transaction failed..
        /// </summary>
        internal static string ExecutingRollbackTransactionFailed {
            get {
                return ResourceManager.GetString("ExecutingRollbackTransactionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing stage &apos;{0}&apos; is completed with errors: &apos;{1}&apos;..
        /// </summary>
        internal static string ExecutingStageIsCompletedWithErrors {
            get {
                return ResourceManager.GetString("ExecutingStageIsCompletedWithErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing stage &apos;{0}&apos; is started..
        /// </summary>
        internal static string ExecutingStageIsStarted {
            get {
                return ResourceManager.GetString("ExecutingStageIsStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing stage &apos;{0}&apos; is successfully completed..
        /// </summary>
        internal static string ExecutingStageIsSuccessfullyCompleted {
            get {
                return ResourceManager.GetString("ExecutingStageIsSuccessfullyCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing transaction failed..
        /// </summary>
        internal static string ExecutingTransactionFailed {
            get {
                return ResourceManager.GetString("ExecutingTransactionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File &apos;{0}&apos; will be overwritten. New source: &apos;{1}&apos;, previous source: {2}..
        /// </summary>
        internal static string FileWillBeOverwritten {
            get {
                return ResourceManager.GetString("FileWillBeOverwritten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application instance &apos;{0}&apos; already installed..
        /// </summary>
        internal static string InstallCommandHandler_AppAlreadyInstalled {
            get {
                return ResourceManager.GetString("InstallCommandHandler_AppAlreadyInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application package &apos;{0}&apos; not found..
        /// </summary>
        internal static string InstallCommandHandler_AppPackageNotFound {
            get {
                return ResourceManager.GetString("InstallCommandHandler_AppPackageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ckeck existing installations.
        /// </summary>
        internal static string InstallCommandHandler_CheckAppInstallation {
            get {
                return ResourceManager.GetString("InstallCommandHandler_CheckAppInstallation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy files of the application.
        /// </summary>
        internal static string InstallCommandHandler_CopyAppFiles {
            get {
                return ResourceManager.GetString("InstallCommandHandler_CopyAppFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find InfinniPlatform.Sdk dependency.
        /// </summary>
        internal static string InstallCommandHandler_FindSdkDependency {
            get {
                return ResourceManager.GetString("InstallCommandHandler_FindSdkDependency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install the application package.
        /// </summary>
        internal static string InstallCommandHandler_InstallAppPackage {
            get {
                return ResourceManager.GetString("InstallCommandHandler_InstallAppPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install the service of the application.
        /// </summary>
        internal static string InstallCommandHandler_InstallAppService {
            get {
                return ResourceManager.GetString("InstallCommandHandler_InstallAppService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install InfinniPlatform package.
        /// </summary>
        internal static string InstallCommandHandler_InstallPlatformPackage {
            get {
                return ResourceManager.GetString("InstallCommandHandler_InstallPlatformPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The platform package &apos;{0}&apos; not found..
        /// </summary>
        internal static string InstallCommandHandler_PlatformPackageNotFound {
            get {
                return ResourceManager.GetString("InstallCommandHandler_PlatformPackageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application package &apos;{0}&apos; does not contain dependency on InfinniPlatform.Sdk..
        /// </summary>
        internal static string InstallCommandHandler_SdkDependencyNotFound {
            get {
                return ResourceManager.GetString("InstallCommandHandler_SdkDependencyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package &apos;{0}&apos; not found..
        /// </summary>
        internal static string PackageNotFound {
            get {
                return ResourceManager.GetString("PackageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registering service file.
        /// </summary>
        internal static string RegisterServiceFileStage {
            get {
                return ResourceManager.GetString("RegisterServiceFileStage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rollback stage &apos;{0}&apos; is completed with errors: &apos;{1}&apos;..
        /// </summary>
        internal static string RollbackStageIsCompletedWithErrors {
            get {
                return ResourceManager.GetString("RollbackStageIsCompletedWithErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rollback stage &apos;{0}&apos; is started..
        /// </summary>
        internal static string RollbackStageIsStarted {
            get {
                return ResourceManager.GetString("RollbackStageIsStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rollback stage &apos;{0}&apos; is successfully completed..
        /// </summary>
        internal static string RollbackStageIsSuccessfullyCompleted {
            get {
                return ResourceManager.GetString("RollbackStageIsSuccessfullyCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not find any applications to start..
        /// </summary>
        internal static string StartCommandHandler_CanNotFindAnyApplicationsToStart {
            get {
                return ResourceManager.GetString("StartCommandHandler_CanNotFindAnyApplicationsToStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find existing installations.
        /// </summary>
        internal static string StartCommandHandler_FindAppInstallations {
            get {
                return ResourceManager.GetString("StartCommandHandler_FindAppInstallations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start the service of the application &apos;{0}&apos;..
        /// </summary>
        internal static string StartCommandHandler_StartAppService {
            get {
                return ResourceManager.GetString("StartCommandHandler_StartAppService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start application services.
        /// </summary>
        internal static string StartCommandHandler_StartAppServices {
            get {
                return ResourceManager.GetString("StartCommandHandler_StartAppServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting the service for the application &apos;{0}&apos; (instance &apos;{1}&apos;)..
        /// </summary>
        internal static string StartingWorkerService {
            get {
                return ResourceManager.GetString("StartingWorkerService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting the service for the application &apos;{0}&apos; (instance &apos;{1}&apos;) completed successfully..
        /// </summary>
        internal static string StartingWorkerServiceCompleted {
            get {
                return ResourceManager.GetString("StartingWorkerServiceCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting the service for the application &apos;{0}&apos; (instance &apos;{1}&apos;) completed with errors: &apos;{2}&apos;..
        /// </summary>
        internal static string StartingWorkerServiceCompletedWithError {
            get {
                return ResourceManager.GetString("StartingWorkerServiceCompletedWithError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not find any applications to get status..
        /// </summary>
        internal static string StatusCommandHandler_CanNotFindAnyApplicationsToGetStatus {
            get {
                return ResourceManager.GetString("StatusCommandHandler_CanNotFindAnyApplicationsToGetStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find existing installations.
        /// </summary>
        internal static string StatusCommandHandler_FindAppInstallations {
            get {
                return ResourceManager.GetString("StatusCommandHandler_FindAppInstallations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieve application statuses.
        /// </summary>
        internal static string StatusCommandHandler_GetStatusAppServices {
            get {
                return ResourceManager.GetString("StatusCommandHandler_GetStatusAppServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not find any applications to stop..
        /// </summary>
        internal static string StopCommandHandler_CanNotFindAnyApplicationsToStop {
            get {
                return ResourceManager.GetString("StopCommandHandler_CanNotFindAnyApplicationsToStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find existing installations.
        /// </summary>
        internal static string StopCommandHandler_FindAppInstallations {
            get {
                return ResourceManager.GetString("StopCommandHandler_FindAppInstallations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop the service of the application &apos;{0}&apos;..
        /// </summary>
        internal static string StopCommandHandler_StopAppServices {
            get {
                return ResourceManager.GetString("StopCommandHandler_StopAppServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopping the service for the application &apos;{0}&apos; (instance &apos;{1}&apos;)..
        /// </summary>
        internal static string StoppingWorkerService {
            get {
                return ResourceManager.GetString("StoppingWorkerService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopping the service for the application &apos;{0}&apos; (instance &apos;{1}&apos;) completed successfully..
        /// </summary>
        internal static string StoppingWorkerServiceCompleted {
            get {
                return ResourceManager.GetString("StoppingWorkerServiceCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopping the service for the application &apos;{0}&apos; (instance &apos;{1}&apos;) completed with errors: &apos;{2}&apos;..
        /// </summary>
        internal static string StoppingWorkerServiceCompletedWithError {
            get {
                return ResourceManager.GetString("StoppingWorkerServiceCompletedWithError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not find any applications to uninstall..
        /// </summary>
        internal static string UninstallCommandHandler_CanNotFindAnyApplicationsToUninstall {
            get {
                return ResourceManager.GetString("UninstallCommandHandler_CanNotFindAnyApplicationsToUninstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete application files.
        /// </summary>
        internal static string UninstallCommandHandler_DeleteAppFiles {
            get {
                return ResourceManager.GetString("UninstallCommandHandler_DeleteAppFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find existing installations.
        /// </summary>
        internal static string UninstallCommandHandler_FindAppInstallations {
            get {
                return ResourceManager.GetString("UninstallCommandHandler_FindAppInstallations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete files of the application &apos;{0}&apos;..
        /// </summary>
        internal static string UninstallCommandHandler_StartDeleteAppFiles {
            get {
                return ResourceManager.GetString("UninstallCommandHandler_StartDeleteAppFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall the service of the application &apos;{0}&apos;..
        /// </summary>
        internal static string UninstallCommandHandler_StartUninstallAppService {
            get {
                return ResourceManager.GetString("UninstallCommandHandler_StartUninstallAppService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall application services.
        /// </summary>
        internal static string UninstallCommandHandler_UninstallAppServices {
            get {
                return ResourceManager.GetString("UninstallCommandHandler_UninstallAppServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must have administrative privileges to run this command..
        /// </summary>
        internal static string YouMustHaveAdministrativePrivilegesToRunThisCommand {
            get {
                return ResourceManager.GetString("YouMustHaveAdministrativePrivilegesToRunThisCommand", resourceCulture);
            }
        }
    }
}
